//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentIt.RentItServices {
    using System;
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gender", Namespace="http://schemas.datacontract.org/2004/07/PersistenceLayerHibernate.Domain")]
    public enum Gender : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Female = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Male = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://schemas.datacontract.org/2004/07/PersistenceLayerHibernate.Domain", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Country : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentIt.RentItServices.Continent ContinentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Iso3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentIt.RentItServices.Continent Continent {
            get {
                return this.ContinentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContinentField, value) != true)) {
                    this.ContinentField = value;
                    this.RaisePropertyChanged("Continent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Iso3 {
            get {
                return this.Iso3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Iso3Field, value) != true)) {
                    this.Iso3Field = value;
                    this.RaisePropertyChanged("Iso3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Continent", Namespace="http://schemas.datacontract.org/2004/07/PersistenceLayerHibernate.Domain", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Continent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/PersistenceLayerHibernate.Domain", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentIt.RentItServices.Media[] BookmarksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentIt.RentItServices.Comment[] CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentIt.RentItServices.Country CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CreditsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FbImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentIt.RentItServices.Gender GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsFacebookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuspendedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<RentIt.RentItServices.Media, int> RatingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentIt.RentItServices.Rental[] RentalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SharedKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentIt.RentItServices.Media[] Bookmarks {
            get {
                return this.BookmarksField;
            }
            set {
                if ((object.ReferenceEquals(this.BookmarksField, value) != true)) {
                    this.BookmarksField = value;
                    this.RaisePropertyChanged("Bookmarks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentIt.RentItServices.Comment[] Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentIt.RentItServices.Country Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Credits {
            get {
                return this.CreditsField;
            }
            set {
                if ((this.CreditsField.Equals(value) != true)) {
                    this.CreditsField = value;
                    this.RaisePropertyChanged("Credits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FbImageUrl {
            get {
                return this.FbImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.FbImageUrlField, value) != true)) {
                    this.FbImageUrlField = value;
                    this.RaisePropertyChanged("FbImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentIt.RentItServices.Gender Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFacebook {
            get {
                return this.IsFacebookField;
            }
            set {
                if ((this.IsFacebookField.Equals(value) != true)) {
                    this.IsFacebookField = value;
                    this.RaisePropertyChanged("IsFacebook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuspended {
            get {
                return this.IsSuspendedField;
            }
            set {
                if ((this.IsSuspendedField.Equals(value) != true)) {
                    this.IsSuspendedField = value;
                    this.RaisePropertyChanged("IsSuspended");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<RentIt.RentItServices.Media, int> Ratings {
            get {
                return this.RatingsField;
            }
            set {
                if ((object.ReferenceEquals(this.RatingsField, value) != true)) {
                    this.RatingsField = value;
                    this.RaisePropertyChanged("Ratings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentIt.RentItServices.Rental[] Rentals {
            get {
                return this.RentalsField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalsField, value) != true)) {
                    this.RentalsField = value;
                    this.RaisePropertyChanged("Rentals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SharedKey {
            get {
                return this.SharedKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.SharedKeyField, value) != true)) {
                    this.SharedKeyField = value;
                    this.RaisePropertyChanged("SharedKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Media", Namespace="http://schemas.datacontract.org/2004/07/PersistenceLayerHibernate.Domain", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RentIt.RentItServices.Movie))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RentIt.RentItServices.Music))]
    public partial class Media : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AverageRatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentIt.RentItServices.Comment[] CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MediaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<RentIt.RentItServices.User, int> RatingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double RentalPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SmallDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThumbnailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentIt.RentItServices.User UploadedByField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AverageRating {
            get {
                return this.AverageRatingField;
            }
            set {
                if ((this.AverageRatingField.Equals(value) != true)) {
                    this.AverageRatingField = value;
                    this.RaisePropertyChanged("AverageRating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentIt.RentItServices.Comment[] Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extension {
            get {
                return this.ExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionField, value) != true)) {
                    this.ExtensionField = value;
                    this.RaisePropertyChanged("Extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((this.IsDeletedField.Equals(value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MediaId {
            get {
                return this.MediaIdField;
            }
            set {
                if ((this.MediaIdField.Equals(value) != true)) {
                    this.MediaIdField = value;
                    this.RaisePropertyChanged("MediaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<RentIt.RentItServices.User, int> Ratings {
            get {
                return this.RatingsField;
            }
            set {
                if ((object.ReferenceEquals(this.RatingsField, value) != true)) {
                    this.RatingsField = value;
                    this.RaisePropertyChanged("Ratings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double RentalPrice {
            get {
                return this.RentalPriceField;
            }
            set {
                if ((this.RentalPriceField.Equals(value) != true)) {
                    this.RentalPriceField = value;
                    this.RaisePropertyChanged("RentalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SmallDescription {
            get {
                return this.SmallDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.SmallDescriptionField, value) != true)) {
                    this.SmallDescriptionField = value;
                    this.RaisePropertyChanged("SmallDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Thumbnail {
            get {
                return this.ThumbnailField;
            }
            set {
                if ((object.ReferenceEquals(this.ThumbnailField, value) != true)) {
                    this.ThumbnailField = value;
                    this.RaisePropertyChanged("Thumbnail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentIt.RentItServices.User UploadedBy {
            get {
                return this.UploadedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UploadedByField, value) != true)) {
                    this.UploadedByField = value;
                    this.RaisePropertyChanged("UploadedBy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comment", Namespace="http://schemas.datacontract.org/2004/07/PersistenceLayerHibernate.Domain", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Comment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CommentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentIt.RentItServices.Media MediaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentIt.RentItServices.User UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CommentId {
            get {
                return this.CommentIdField;
            }
            set {
                if ((this.CommentIdField.Equals(value) != true)) {
                    this.CommentIdField = value;
                    this.RaisePropertyChanged("CommentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentIt.RentItServices.Media Media {
            get {
                return this.MediaField;
            }
            set {
                if ((object.ReferenceEquals(this.MediaField, value) != true)) {
                    this.MediaField = value;
                    this.RaisePropertyChanged("Media");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentIt.RentItServices.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rental", Namespace="http://schemas.datacontract.org/2004/07/PersistenceLayerHibernate.Domain", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Rental : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentIt.RentItServices.Media MediaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RentalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentIt.RentItServices.User UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentIt.RentItServices.Media Media {
            get {
                return this.MediaField;
            }
            set {
                if ((object.ReferenceEquals(this.MediaField, value) != true)) {
                    this.MediaField = value;
                    this.RaisePropertyChanged("Media");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RentalId {
            get {
                return this.RentalIdField;
            }
            set {
                if ((this.RentalIdField.Equals(value) != true)) {
                    this.RentalIdField = value;
                    this.RaisePropertyChanged("RentalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentIt.RentItServices.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movie", Namespace="http://schemas.datacontract.org/2004/07/PersistenceLayerHibernate.Domain", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Movie : RentIt.RentItServices.Media {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentIt.RentItServices.MovieCategory CategoryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentIt.RentItServices.MovieCategory Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Music", Namespace="http://schemas.datacontract.org/2004/07/PersistenceLayerHibernate.Domain", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Music : RentIt.RentItServices.Media {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentIt.RentItServices.MusicCategory CategoryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentIt.RentItServices.MusicCategory Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MovieCategory", Namespace="http://schemas.datacontract.org/2004/07/PersistenceLayerHibernate.Domain", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class MovieCategory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MusicCategory", Namespace="http://schemas.datacontract.org/2004/07/PersistenceLayerHibernate.Domain", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class MusicCategory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RentItServices.IRentitService")]
    public interface IRentitService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/CreateUser", ReplyAction="http://tempuri.org/IRentitService/CreateUserResponse")]
        System.Tuple<bool, string> CreateUser(string email, string password, RentIt.RentItServices.Gender gender, RentIt.RentItServices.Country country, int age);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/GetUser", ReplyAction="http://tempuri.org/IRentitService/GetUserResponse")]
        System.Tuple<RentIt.RentItServices.User, string> GetUser(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/UpdateUser", ReplyAction="http://tempuri.org/IRentitService/UpdateUserResponse")]
        System.Tuple<bool, string> UpdateUser(RentIt.RentItServices.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/Login", ReplyAction="http://tempuri.org/IRentitService/LoginResponse")]
        System.Tuple<bool, RentIt.RentItServices.User, string, string> Login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/Logout", ReplyAction="http://tempuri.org/IRentitService/LogoutResponse")]
        System.Tuple<bool, string> Logout(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/SearchMediaFromTitle", ReplyAction="http://tempuri.org/IRentitService/SearchMediaFromTitleResponse")]
        System.Tuple<RentIt.RentItServices.Media[], string> SearchMediaFromTitle(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/SearchMovieFromCategory", ReplyAction="http://tempuri.org/IRentitService/SearchMovieFromCategoryResponse")]
        System.Tuple<RentIt.RentItServices.Media[], string> SearchMovieFromCategory(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/SearchMusicFromCategory", ReplyAction="http://tempuri.org/IRentitService/SearchMusicFromCategoryResponse")]
        System.Tuple<RentIt.RentItServices.Media[], string> SearchMusicFromCategory(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/GetMedia", ReplyAction="http://tempuri.org/IRentitService/GetMediaResponse")]
        System.Tuple<RentIt.RentItServices.Media, string> GetMedia(int mediaID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/RentMedia", ReplyAction="http://tempuri.org/IRentitService/RentMediaResponse")]
        System.Tuple<bool, string> RentMedia(int mediaID, RentIt.RentItServices.User user, double duration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/BookmarkMedia", ReplyAction="http://tempuri.org/IRentitService/BookmarkMediaResponse")]
        System.Tuple<bool, string> BookmarkMedia(int mediaId, RentIt.RentItServices.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/CommentMedia", ReplyAction="http://tempuri.org/IRentitService/CommentMediaResponse")]
        System.Tuple<bool, string> CommentMedia(int mediaId, RentIt.RentItServices.User user, string title, string comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/RateMedia", ReplyAction="http://tempuri.org/IRentitService/RateMediaResponse")]
        System.Tuple<bool, string> RateMedia(int mediaId, RentIt.RentItServices.User user, int rating);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/UpdateMedia", ReplyAction="http://tempuri.org/IRentitService/UpdateMediaResponse")]
        System.Tuple<bool, string> UpdateMedia(RentIt.RentItServices.Media media);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/DeleteMedia", ReplyAction="http://tempuri.org/IRentitService/DeleteMediaResponse")]
        System.Tuple<bool, string> DeleteMedia(int mediaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/GetGenderAnalytics", ReplyAction="http://tempuri.org/IRentitService/GetGenderAnalyticsResponse")]
        System.Tuple<double, double, string> GetGenderAnalytics(RentIt.RentItServices.Media media);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/GetAgeAnalytics", ReplyAction="http://tempuri.org/IRentitService/GetAgeAnalyticsResponse")]
        System.Tuple<double[], string> GetAgeAnalytics(RentIt.RentItServices.Media media);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/GetContinentAnalytics", ReplyAction="http://tempuri.org/IRentitService/GetContinentAnalyticsResponse")]
        System.Tuple<double[], string> GetContinentAnalytics(RentIt.RentItServices.Media media);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/IsRented", ReplyAction="http://tempuri.org/IRentitService/IsRentedResponse")]
        System.Tuple<bool, string> IsRented(int mediaId, RentIt.RentItServices.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/GetRentalHistory", ReplyAction="http://tempuri.org/IRentitService/GetRentalHistoryResponse")]
        System.Tuple<RentIt.RentItServices.Rental[], string> GetRentalHistory(RentIt.RentItServices.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/FacebookLogin", ReplyAction="http://tempuri.org/IRentitService/FacebookLoginResponse")]
        System.Tuple<bool, RentIt.RentItServices.User, string, string> FacebookLogin(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/GetCountries", ReplyAction="http://tempuri.org/IRentitService/GetCountriesResponse")]
        RentIt.RentItServices.Country[] GetCountries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/GetMovieCategories", ReplyAction="http://tempuri.org/IRentitService/GetMovieCategoriesResponse")]
        RentIt.RentItServices.MovieCategory[] GetMovieCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/GetMusicCategories", ReplyAction="http://tempuri.org/IRentitService/GetMusicCategoriesResponse")]
        RentIt.RentItServices.MusicCategory[] GetMusicCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/GetUserBookmarks", ReplyAction="http://tempuri.org/IRentitService/GetUserBookmarksResponse")]
        System.Tuple<RentIt.RentItServices.Media[], string> GetUserBookmarks(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/RemoveBookmark", ReplyAction="http://tempuri.org/IRentitService/RemoveBookmarkResponse")]
        System.Tuple<bool, string> RemoveBookmark(string email, RentIt.RentItServices.Media media);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/GetMostPopularMedia", ReplyAction="http://tempuri.org/IRentitService/GetMostPopularMediaResponse")]
        System.Tuple<RentIt.RentItServices.Media[], string> GetMostPopularMedia(int amountOfResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/GetAllUsers", ReplyAction="http://tempuri.org/IRentitService/GetAllUsersResponse")]
        System.Tuple<RentIt.RentItServices.User[], string> GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/GetAllMedia", ReplyAction="http://tempuri.org/IRentitService/GetAllMediaResponse")]
        System.Tuple<RentIt.RentItServices.Media[], string> GetAllMedia();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/UploadByUrl", ReplyAction="http://tempuri.org/IRentitService/UploadByUrlResponse")]
        System.Tuple<bool, string> UploadByUrl(RentIt.RentItServices.Media media);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/GetMediaUrl", ReplyAction="http://tempuri.org/IRentitService/GetMediaUrlResponse")]
        System.Tuple<string, string> GetMediaUrl(int mediaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/SuspendUser", ReplyAction="http://tempuri.org/IRentitService/SuspendUserResponse")]
        System.Tuple<bool, string> SuspendUser(string UserEmail);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRentitServiceChannel : RentIt.RentItServices.IRentitService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RentitServiceClient : System.ServiceModel.ClientBase<RentIt.RentItServices.IRentitService>, RentIt.RentItServices.IRentitService {
        
        public RentitServiceClient() {
        }
        
        public RentitServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RentitServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentitServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentitServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Tuple<bool, string> CreateUser(string email, string password, RentIt.RentItServices.Gender gender, RentIt.RentItServices.Country country, int age) {
            return base.Channel.CreateUser(email, password, gender, country, age);
        }
        
        public System.Tuple<RentIt.RentItServices.User, string> GetUser(string email) {
            return base.Channel.GetUser(email);
        }
        
        public System.Tuple<bool, string> UpdateUser(RentIt.RentItServices.User user) {
            return base.Channel.UpdateUser(user);
        }
        
        public System.Tuple<bool, RentIt.RentItServices.User, string, string> Login(string email, string password) {
            return base.Channel.Login(email, password);
        }
        
        public System.Tuple<bool, string> Logout(string email) {
            return base.Channel.Logout(email);
        }
        
        public System.Tuple<RentIt.RentItServices.Media[], string> SearchMediaFromTitle(string title) {
            return base.Channel.SearchMediaFromTitle(title);
        }
        
        public System.Tuple<RentIt.RentItServices.Media[], string> SearchMovieFromCategory(string category) {
            return base.Channel.SearchMovieFromCategory(category);
        }
        
        public System.Tuple<RentIt.RentItServices.Media[], string> SearchMusicFromCategory(string category) {
            return base.Channel.SearchMusicFromCategory(category);
        }
        
        public System.Tuple<RentIt.RentItServices.Media, string> GetMedia(int mediaID) {
            return base.Channel.GetMedia(mediaID);
        }
        
        public System.Tuple<bool, string> RentMedia(int mediaID, RentIt.RentItServices.User user, double duration) {
            return base.Channel.RentMedia(mediaID, user, duration);
        }
        
        public System.Tuple<bool, string> BookmarkMedia(int mediaId, RentIt.RentItServices.User user) {
            return base.Channel.BookmarkMedia(mediaId, user);
        }
        
        public System.Tuple<bool, string> CommentMedia(int mediaId, RentIt.RentItServices.User user, string title, string comment) {
            return base.Channel.CommentMedia(mediaId, user, title, comment);
        }
        
        public System.Tuple<bool, string> RateMedia(int mediaId, RentIt.RentItServices.User user, int rating) {
            return base.Channel.RateMedia(mediaId, user, rating);
        }
        
        public System.Tuple<bool, string> UpdateMedia(RentIt.RentItServices.Media media) {
            return base.Channel.UpdateMedia(media);
        }
        
        public System.Tuple<bool, string> DeleteMedia(int mediaId) {
            return base.Channel.DeleteMedia(mediaId);
        }
        
        public System.Tuple<double, double, string> GetGenderAnalytics(RentIt.RentItServices.Media media) {
            return base.Channel.GetGenderAnalytics(media);
        }
        
        public System.Tuple<double[], string> GetAgeAnalytics(RentIt.RentItServices.Media media) {
            return base.Channel.GetAgeAnalytics(media);
        }
        
        public System.Tuple<double[], string> GetContinentAnalytics(RentIt.RentItServices.Media media) {
            return base.Channel.GetContinentAnalytics(media);
        }
        
        public System.Tuple<bool, string> IsRented(int mediaId, RentIt.RentItServices.User user) {
            return base.Channel.IsRented(mediaId, user);
        }
        
        public System.Tuple<RentIt.RentItServices.Rental[], string> GetRentalHistory(RentIt.RentItServices.User user) {
            return base.Channel.GetRentalHistory(user);
        }
        
        public System.Tuple<bool, RentIt.RentItServices.User, string, string> FacebookLogin(string token) {
            return base.Channel.FacebookLogin(token);
        }
        
        public RentIt.RentItServices.Country[] GetCountries() {
            return base.Channel.GetCountries();
        }
        
        public RentIt.RentItServices.MovieCategory[] GetMovieCategories() {
            return base.Channel.GetMovieCategories();
        }
        
        public RentIt.RentItServices.MusicCategory[] GetMusicCategories() {
            return base.Channel.GetMusicCategories();
        }
        
        public System.Tuple<RentIt.RentItServices.Media[], string> GetUserBookmarks(string email) {
            return base.Channel.GetUserBookmarks(email);
        }
        
        public System.Tuple<bool, string> RemoveBookmark(string email, RentIt.RentItServices.Media media) {
            return base.Channel.RemoveBookmark(email, media);
        }
        
        public System.Tuple<RentIt.RentItServices.Media[], string> GetMostPopularMedia(int amountOfResults) {
            return base.Channel.GetMostPopularMedia(amountOfResults);
        }
        
        public System.Tuple<RentIt.RentItServices.User[], string> GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Tuple<RentIt.RentItServices.Media[], string> GetAllMedia() {
            return base.Channel.GetAllMedia();
        }
        
        public System.Tuple<bool, string> UploadByUrl(RentIt.RentItServices.Media media) {
            return base.Channel.UploadByUrl(media);
        }
        
        public System.Tuple<string, string> GetMediaUrl(int mediaId) {
            return base.Channel.GetMediaUrl(mediaId);
        }
        
        public System.Tuple<bool, string> SuspendUser(string UserEmail) {
            return base.Channel.SuspendUser(UserEmail);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RentItServices.IRentItFileService")]
    public interface IRentItFileService {
        
        // CODEGEN: Generating message contract since the wrapper name (UploadFileRequest) of message UploadFileRequest does not match the default value (UploadFile)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItFileService/UploadFile", ReplyAction="http://tempuri.org/IRentItFileService/UploadFileResponse")]
        RentIt.RentItServices.UploadFileResult UploadFile(RentIt.RentItServices.UploadFileRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (DownloadFileRequest) of message DownloadFileRequest does not match the default value (DownloadFile)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentItFileService/DownloadFile", ReplyAction="http://tempuri.org/IRentItFileService/DownloadFileResponse")]
        RentIt.RentItServices.DownloadFileResult DownloadFile(RentIt.RentItServices.DownloadFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFileRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadFileRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public System.Tuple<string, RentIt.RentItServices.Media, RentIt.RentItServices.User> MediaLoginAndUserTuple;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileStream;
        
        public UploadFileRequest() {
        }
        
        public UploadFileRequest(System.Tuple<string, RentIt.RentItServices.Media, RentIt.RentItServices.User> MediaLoginAndUserTuple, System.IO.Stream FileStream) {
            this.MediaLoginAndUserTuple = MediaLoginAndUserTuple;
            this.FileStream = FileStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFileResult", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadFileResult {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Success;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ErrorMessage;
        
        public UploadFileResult() {
        }
        
        public UploadFileResult(bool Success, string ErrorMessage) {
            this.Success = Success;
            this.ErrorMessage = ErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadFileRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadFileRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public System.Tuple<string, RentIt.RentItServices.Media, RentIt.RentItServices.User> MediaLoginAndUserTuple;
        
        public DownloadFileRequest() {
        }
        
        public DownloadFileRequest(System.Tuple<string, RentIt.RentItServices.Media, RentIt.RentItServices.User> MediaLoginAndUserTuple) {
            this.MediaLoginAndUserTuple = MediaLoginAndUserTuple;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadFileResult", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadFileResult {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileDownload;
        
        public DownloadFileResult() {
        }
        
        public DownloadFileResult(System.IO.Stream FileDownload) {
            this.FileDownload = FileDownload;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRentItFileServiceChannel : RentIt.RentItServices.IRentItFileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RentItFileServiceClient : System.ServiceModel.ClientBase<RentIt.RentItServices.IRentItFileService>, RentIt.RentItServices.IRentItFileService {
        
        public RentItFileServiceClient() {
        }
        
        public RentItFileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RentItFileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentItFileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentItFileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentIt.RentItServices.UploadFileResult RentIt.RentItServices.IRentItFileService.UploadFile(RentIt.RentItServices.UploadFileRequest request) {
            return base.Channel.UploadFile(request);
        }
        
        public bool UploadFile(System.Tuple<string, RentIt.RentItServices.Media, RentIt.RentItServices.User> MediaLoginAndUserTuple, System.IO.Stream FileStream, out string ErrorMessage) {
            RentIt.RentItServices.UploadFileRequest inValue = new RentIt.RentItServices.UploadFileRequest();
            inValue.MediaLoginAndUserTuple = MediaLoginAndUserTuple;
            inValue.FileStream = FileStream;
            RentIt.RentItServices.UploadFileResult retVal = ((RentIt.RentItServices.IRentItFileService)(this)).UploadFile(inValue);
            ErrorMessage = retVal.ErrorMessage;
            return retVal.Success;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentIt.RentItServices.DownloadFileResult RentIt.RentItServices.IRentItFileService.DownloadFile(RentIt.RentItServices.DownloadFileRequest request) {
            return base.Channel.DownloadFile(request);
        }
        
        public System.IO.Stream DownloadFile(System.Tuple<string, RentIt.RentItServices.Media, RentIt.RentItServices.User> MediaLoginAndUserTuple) {
            RentIt.RentItServices.DownloadFileRequest inValue = new RentIt.RentItServices.DownloadFileRequest();
            inValue.MediaLoginAndUserTuple = MediaLoginAndUserTuple;
            RentIt.RentItServices.DownloadFileResult retVal = ((RentIt.RentItServices.IRentItFileService)(this)).DownloadFile(inValue);
            return retVal.FileDownload;
        }
    }
}
