//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentIt.RentItServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/PersistenceLayerHibernate.Domain")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Media", Namespace="http://schemas.datacontract.org/2004/07/PersistenceLayerHibernate.Domain")]
    [System.SerializableAttribute()]
    public partial class Media : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RentItServices.IRentitService")]
    public interface IRentitService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/CreateUser", ReplyAction="http://tempuri.org/IRentitService/CreateUserResponse")]
        System.Tuple<bool, string> CreateUser(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/GetUser", ReplyAction="http://tempuri.org/IRentitService/GetUserResponse")]
        System.Tuple<RentIt.RentItServices.User, string> GetUser(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/UpdateUser", ReplyAction="http://tempuri.org/IRentitService/UpdateUserResponse")]
        System.Tuple<bool, string> UpdateUser(RentIt.RentItServices.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/Login", ReplyAction="http://tempuri.org/IRentitService/LoginResponse")]
        System.Tuple<bool, string> Login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/Logout", ReplyAction="http://tempuri.org/IRentitService/LogoutResponse")]
        System.Tuple<bool, string> Logout(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/IsLoggedIn", ReplyAction="http://tempuri.org/IRentitService/IsLoggedInResponse")]
        System.Tuple<bool, string> IsLoggedIn(RentIt.RentItServices.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/SearchMediaFromTitle", ReplyAction="http://tempuri.org/IRentitService/SearchMediaFromTitleResponse")]
        System.Tuple<RentIt.RentItServices.Media[], string> SearchMediaFromTitle(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/SearchMediaFromCategory", ReplyAction="http://tempuri.org/IRentitService/SearchMediaFromCategoryResponse")]
        System.Tuple<RentIt.RentItServices.Media[], string> SearchMediaFromCategory(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/GetMedia", ReplyAction="http://tempuri.org/IRentitService/GetMediaResponse")]
        System.Tuple<RentIt.RentItServices.Media, string> GetMedia(int mediaID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/RentMedia", ReplyAction="http://tempuri.org/IRentitService/RentMediaResponse")]
        System.Tuple<bool, string> RentMedia(int mediaID, RentIt.RentItServices.User user, int credits);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/CommentMedia", ReplyAction="http://tempuri.org/IRentitService/CommentMediaResponse")]
        System.Tuple<bool, string> CommentMedia(int mediaId, RentIt.RentItServices.User user, string comment);
        
        // CODEGEN: Generating message contract since element name rating from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/RateMedia", ReplyAction="http://tempuri.org/IRentitService/RateMediaResponse")]
        RentIt.RentItServices.RateMediaResponse RateMedia(RentIt.RentItServices.RateMediaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/UploadMedia", ReplyAction="http://tempuri.org/IRentitService/UploadMediaResponse")]
        System.Tuple<bool, string> UploadMedia(RentIt.RentItServices.Media media, RentIt.RentItServices.User admin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentitService/UpdateMedia", ReplyAction="http://tempuri.org/IRentitService/UpdateMediaResponse")]
        System.Tuple<bool, string> UpdateMedia(RentIt.RentItServices.Media media);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RateMediaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RateMedia", Namespace="http://tempuri.org/", Order=0)]
        public RentIt.RentItServices.RateMediaRequestBody Body;
        
        public RateMediaRequest() {
        }
        
        public RateMediaRequest(RentIt.RentItServices.RateMediaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RateMediaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int mediaId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public RentIt.RentItServices.User user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string rating;
        
        public RateMediaRequestBody() {
        }
        
        public RateMediaRequestBody(int mediaId, RentIt.RentItServices.User user, string rating) {
            this.mediaId = mediaId;
            this.user = user;
            this.rating = rating;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RateMediaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RateMediaResponse", Namespace="http://tempuri.org/", Order=0)]
        public RentIt.RentItServices.RateMediaResponseBody Body;
        
        public RateMediaResponse() {
        }
        
        public RateMediaResponse(RentIt.RentItServices.RateMediaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RateMediaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Tuple<bool, string> RateMediaResult;
        
        public RateMediaResponseBody() {
        }
        
        public RateMediaResponseBody(System.Tuple<bool, string> RateMediaResult) {
            this.RateMediaResult = RateMediaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRentitServiceChannel : RentIt.RentItServices.IRentitService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RentitServiceClient : System.ServiceModel.ClientBase<RentIt.RentItServices.IRentitService>, RentIt.RentItServices.IRentitService {
        
        public RentitServiceClient() {
        }
        
        public RentitServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RentitServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentitServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentitServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Tuple<bool, string> CreateUser(string email, string password) {
            return base.Channel.CreateUser(email, password);
        }
        
        public System.Tuple<RentIt.RentItServices.User, string> GetUser(string email) {
            return base.Channel.GetUser(email);
        }
        
        public System.Tuple<bool, string> UpdateUser(RentIt.RentItServices.User user) {
            return base.Channel.UpdateUser(user);
        }
        
        public System.Tuple<bool, string> Login(string email, string password) {
            return base.Channel.Login(email, password);
        }
        
        public System.Tuple<bool, string> Logout(string email) {
            return base.Channel.Logout(email);
        }
        
        public System.Tuple<bool, string> IsLoggedIn(RentIt.RentItServices.User user) {
            return base.Channel.IsLoggedIn(user);
        }
        
        public System.Tuple<RentIt.RentItServices.Media[], string> SearchMediaFromTitle(string title) {
            return base.Channel.SearchMediaFromTitle(title);
        }
        
        public System.Tuple<RentIt.RentItServices.Media[], string> SearchMediaFromCategory(string category) {
            return base.Channel.SearchMediaFromCategory(category);
        }
        
        public System.Tuple<RentIt.RentItServices.Media, string> GetMedia(int mediaID) {
            return base.Channel.GetMedia(mediaID);
        }
        
        public System.Tuple<bool, string> RentMedia(int mediaID, RentIt.RentItServices.User user, int credits) {
            return base.Channel.RentMedia(mediaID, user, credits);
        }
        
        public System.Tuple<bool, string> CommentMedia(int mediaId, RentIt.RentItServices.User user, string comment) {
            return base.Channel.CommentMedia(mediaId, user, comment);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentIt.RentItServices.RateMediaResponse RentIt.RentItServices.IRentitService.RateMedia(RentIt.RentItServices.RateMediaRequest request) {
            return base.Channel.RateMedia(request);
        }
        
        public System.Tuple<bool, string> RateMedia(int mediaId, RentIt.RentItServices.User user, string rating) {
            RentIt.RentItServices.RateMediaRequest inValue = new RentIt.RentItServices.RateMediaRequest();
            inValue.Body = new RentIt.RentItServices.RateMediaRequestBody();
            inValue.Body.mediaId = mediaId;
            inValue.Body.user = user;
            inValue.Body.rating = rating;
            RentIt.RentItServices.RateMediaResponse retVal = ((RentIt.RentItServices.IRentitService)(this)).RateMedia(inValue);
            return retVal.Body.RateMediaResult;
        }
        
        public System.Tuple<bool, string> UploadMedia(RentIt.RentItServices.Media media, RentIt.RentItServices.User admin) {
            return base.Channel.UploadMedia(media, admin);
        }
        
        public System.Tuple<bool, string> UpdateMedia(RentIt.RentItServices.Media media) {
            return base.Channel.UpdateMedia(media);
        }
    }
}
